### PR TITLE
Pin cloudflared version

### PR DESCRIPTION
**Pull request by michaltk**
seems like it’s no longer avail in the latest

### CODE REVIEW

**Comment by tikotzky** [comment]
I’m assuming this is temp until cloudflare fixes their build?

**Comment by michaltk** [comment]
Yep assuming they will add it.
Unless we can use a diff compatible asset?

**Comment by tikotzky** [comment]
Seems like it’s just a bad build. Looks like it’s a missing the.binaries for a few of the different platforms.

**Comment by michaltk** [comment]
https://github.com/cloudflare/cloudflared/issues/950

**Pull request merged**
